<h1>Registro de Cliente - Visualização</h1>
    <table class="table table-striped">
        <tr>
            <th>Nome:</th>
            <td>
                <?=$arrayClient['name']?>
            </td>
        </tr>
        <tr>
            <th>Email:</th>
            <td>
                <?=$arrayClient['email']?>
            </td>
        </tr>
        <tr>
            <th>Phone:</th>
            <td>
                <?=$arrayClient['phone']?>
            </td>
        </tr>
        <tr>
            <th>Genero:</th>
            <td>
                <?=$arrayClient['gender']?>
            </td>
        </tr>
        <tr>
            <th>Termo:</th>
            <td>
                <?=$arrayClient['accept']?>
            </td>
        </tr>
    </table>